title: "mohamed mOoka | Cybersecurity Analyst"
description: "Threat hunter & SOC specialist focused on proactive defense and incident response"
baseurl: ""
url: "https://mohamedmOoka.github.io"

theme: null
plugins: []

author: "mohamed mOoka"
github_username: "mohamedmOoka"
linkedin_username: "mohamed-mooka"
email: "mohamed.ashraf.abdallah65@gmail.com"
